linters:
  enable:
    - errcheck
    - staticcheck
    - unused
    - govet
    - ineffassign
    - gofmt
    - goimports
    - gosimple
    - misspell

linters-settings:
  errcheck:
    exclude-functions:
      - (io.Closer).Close
      - (net/http.ResponseWriter).Write

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: _test\.go
      linters:
        - unused
