//! cursor's create-time preseed — a port of `internal/ext/rc/preseed_cursor.go`.
//!
//! cursor-agent has no protocol the hub can subscribe to, but it DOES run
//! user-configured hooks on every meaningful event of a turn. Those hooks are the
//! only live signal a cursor session produces, so the preseed writes two files:
//!
//! * `~/.shed-rc-hub/cursor-hook.sh` — **hub-owned, overwritten every time**
//!   (0755). It POSTs each hook payload to the hub's loopback ingest route and is
//!   deliberately mute: cursor reads a hook's stdout as a VERDICT, so anything
//!   printed would steer the agent.
//! * `~/.cursor/hooks.json` — **user-owned, merged never clobbered**: existing
//!   entries survive, ours is appended only when absent (matched on the script
//!   path, so a re-run is idempotent), and a valid-but-unexpected SHAPE is
//!   refused rather than overwritten.
//!
//! Both are raw-bytes parity surfaces (plan 009 §3.5) — the script because a
//! mixed fleet rewrites it on every create, `hooks.json` because it is merged in
//! place — so the script bytes are Go's VERBATIM (including its `shed-ext-rc`
//! self-reference, which is content, not provenance) and the config goes through
//! [`super::go_json`].

use std::os::unix::fs::{DirBuilderExt, MetadataExt};
use std::path::{Path, PathBuf};

use shed_core::rc_agents::shell_quote_always;

use super::go_json::{marshal_indent, GoObject, GoValue};
use super::ops::GetEnv;
use super::preseed::PreseedError;
use super::trust::{atomic_write, lock_sibling, read_json_object};

/// The hub's loopback address (`rc.HubAddr`, `hub.go:62`). The hub itself is NOT
/// ported (plan 009 §0), so the constant is duplicated here rather than imported
/// — its value is pinned cross-implementation by the parity harness, which
/// byte-compares the script this interpolates it into.
pub const HUB_ADDR: &str = "127.0.0.1:1029";

/// The per-user hub state directory basename under `$HOME` (`hubDirName`,
/// `hub.go:65`) — where the hub-owned hook script lives, deliberately NOT inside
/// `~/.cursor`.
pub const HUB_DIR_NAME: &str = ".shed-rc-hub";

/// The hub-owned hook script's basename inside [`HUB_DIR_NAME`]
/// (`cursorHookScriptName`, `preseed_cursor.go:40`).
pub const CURSOR_HOOK_SCRIPT_NAME: &str = "cursor-hook.sh";

/// The `hooks.json` schema version cursor expects, written only when the file
/// does not already declare one (`cursorHooksConfigVersion`,
/// `preseed_cursor.go:43`).
const CURSOR_HOOKS_CONFIG_VERSION: &str = "1";

/// `os.CreateTemp` patterns for the two files (`preseed_cursor.go:163,283`).
pub const SCRIPT_TMP_PATTERN: &str = ".cursor-hook.sh.*.tmp";
pub const HOOKS_TMP_PATTERN: &str = ".hooks.json.*.tmp";

/// Mode of the hook script — cursor execs it directly.
const SCRIPT_MODE: u32 = 0o755;

/// The hook events wired to the hub's script, **in a fixed order** so the written
/// config is deterministic (`cursorHookEvents`, `preseed_cursor.go:70`).
///
/// `postToolUse` is wired for the COUNTER, not its payload; `afterAgentThought`,
/// `beforeReadFile`, `workspaceOpen` and `beforeShellExecution` are deliberately
/// NOT wired (see the Go original for the per-event rationale).
pub const CURSOR_HOOK_EVENTS: [&str; 10] = [
    "sessionStart",
    "beforeSubmitPrompt",
    "preToolUse",
    "afterShellExecution",
    "afterFileEdit",
    "postToolUse",
    "postToolUseFailure",
    "afterAgentResponse",
    "stop",
    "sessionEnd",
];

// The script, split exactly where Go concatenates `HubAddr` (`preseed_cursor.go:
// 196-215`). Written as escaped (not raw) string literals so the tabs on the
// curl continuation lines — which ARE part of the byte-parity surface — cannot be
// mangled by an editor or a reformat.
const SCRIPT_HEAD: &str = "#!/bin/sh\n\
# shed rc hub \u{2014} cursor hook relay. GENERATED by shed-ext-rc (PreseedCursorHooks);\n\
# rewritten on every rc session create, so local edits do not survive.\n\
#\n\
# Reads one hook payload on stdin and POSTs it to the shed rc hub's ingest route.\n\
# ALWAYS exits 0 with EMPTY stdout: cursor treats hook stdout as a verdict, so this\n\
# script must never influence the agent. A hub that is down/slow costs at most the\n\
# curl timeouts below and changes nothing about the run.\n\
#\n\
# --noproxy '*' is load-bearing: the hub is on loopback, and an http_proxy in the\n\
# environment would otherwise send this session's prompts and command output to it.\n\
[ -n \"${SHED_RC_SLUG}\" ] || exit 0\n\
curl --silent --output /dev/null --noproxy '*' --globoff \\\n\
\t--connect-timeout 1 --max-time 2 \\\n\
\t-X POST -H 'Content-Type: application/json' --data-binary @- \\\n\
\t\"http://";
const SCRIPT_TAIL: &str = "/v1/ingest/cursor?slug=${SHED_RC_SLUG}&event=$1\" || true\nexit 0\n";

/// The hook script's exact bytes (`cursorHookScript`, `preseed_cursor.go:196`).
pub fn cursor_hook_script() -> String {
    format!("{SCRIPT_HEAD}{HUB_ADDR}{SCRIPT_TAIL}")
}

/// `~/.shed-rc-hub/cursor-hook.sh`.
pub fn cursor_script_path(home: &str) -> PathBuf {
    Path::new(home)
        .join(HUB_DIR_NAME)
        .join(CURSOR_HOOK_SCRIPT_NAME)
}

/// `~/.cursor/hooks.json`.
pub fn cursor_hooks_path(home: &str) -> PathBuf {
    Path::new(home).join(".cursor").join("hooks.json")
}

/// Write the hub's cursor hook script and merge it into `~/.cursor/hooks.json`
/// (`PreseedCursorHooks`, `preseed_cursor.go:126`).
///
/// `workdir` is unused (cursor hooks are global, unlike claude's per-project
/// trust) and is accepted only to satisfy the shared preseed signature.
pub fn preseed_cursor_hooks(workdir: &str, env: GetEnv) -> Result<(), PreseedError> {
    preseed_cursor_hooks_with(workdir, env, &stat_same_device)
}

/// The device check as an injected seam — the ONE thing in this file that cannot
/// be exercised with a temp dir (Go solves it with a package var,
/// `preseed_cursor.go:97`).
type SameDevice = dyn Fn(&Path, &Path) -> std::io::Result<bool>;

pub(crate) fn preseed_cursor_hooks_with(
    _workdir: &str,
    env: GetEnv,
    same_device: &SameDevice,
) -> Result<(), PreseedError> {
    let home = env("HOME");
    if home.is_empty() {
        return Err(PreseedError::failed(
            "no HOME; skipping cursor hook preseed",
        ));
    }

    let script_path = write_cursor_hook_script(&home)?;

    let cursor_dir = Path::new(&home).join(".cursor");
    // MkdirAll FIRST so the device check has something to stat: a fresh shed has
    // no ~/.cursor until cursor-agent first runs, and a directory we just created
    // under $HOME is on $HOME's device by construction.
    std::fs::DirBuilder::new()
        .recursive(true)
        .mode(0o700)
        .create(&cursor_dir)
        .map_err(|e| PreseedError::failed(format!("creating {}: {e}", cursor_dir.display())))?;
    let same = same_device(&cursor_dir, Path::new(&home)).map_err(|e| {
        PreseedError::failed(format!(
            "checking whether {} is a mount: {e}",
            cursor_dir.display()
        ))
    })?;
    if !same {
        // The hooks.json half is skipped; the script half is already written and
        // is inert until something references it.
        return Err(PreseedError::CursorForeignDevice);
    }
    merge_cursor_hooks_config(&cursor_dir.join("hooks.json"), &script_path)
}

/// `st_dev` equality (`statSameDevice`, `preseed_cursor.go:102`). A missing path
/// is an ERROR, not a verdict.
fn stat_same_device(a: &Path, b: &Path) -> std::io::Result<bool> {
    Ok(std::fs::metadata(a)?.dev() == std::fs::metadata(b)?.dev())
}

/// Write `~/.shed-rc-hub/cursor-hook.sh` (0755) and return its path
/// (`writeCursorHookScript`, `preseed_cursor.go:157`). **Overwrite-always**: the
/// script is hub-owned, so the binary running now defines what it contains and a
/// stale script from an older build must never survive.
fn write_cursor_hook_script(home: &str) -> Result<PathBuf, PreseedError> {
    let dir = Path::new(home).join(HUB_DIR_NAME);
    std::fs::DirBuilder::new()
        .recursive(true)
        .mode(0o700)
        .create(&dir)
        .map_err(|e| PreseedError::failed(format!("creating {}: {e}", dir.display())))?;
    let path = dir.join(CURSOR_HOOK_SCRIPT_NAME);
    atomic_write(
        &path,
        SCRIPT_TMP_PATTERN,
        cursor_hook_script().as_bytes(),
        SCRIPT_MODE,
    )?;
    Ok(path)
}

/// Merge the hub's hook entry into `hooks.json` for every wired event, preserving
/// everything else (`mergeCursorHooksConfig`, `preseed_cursor.go:228`).
///
/// Merge rules, all of them Go's:
///
/// * the document round-trips as raw JSON, so unknown top-level keys and unknown
///   per-entry fields survive verbatim;
/// * `version` is written only when absent;
/// * each event's array keeps its entries IN ORDER with ours appended; a re-run
///   finds ours by script path and changes nothing;
/// * an unexpected SHAPE (a non-object `hooks`, a non-array event) is refused by
///   NAME — the tempting `hooks, _ := raw.(map[string]any)` would silently delete
///   config that is perfectly valid, just shaped differently.
fn merge_cursor_hooks_config(path: &Path, script_path: &Path) -> Result<(), PreseedError> {
    let _lock = lock_sibling(path)
        .map_err(|e| PreseedError::failed(format!("locking cursor hooks: {e}")))?;

    let (mut config, mode) = read_json_object(path)?;

    config
        .entry("version".to_string())
        .or_insert_with(|| GoValue::Number(CURSOR_HOOKS_CONFIG_VERSION.to_string()));

    let mut hooks = match config.remove("hooks") {
        None => GoObject::new(),
        Some(GoValue::Object(obj)) => obj,
        Some(other) => {
            return Err(PreseedError::failed(format!(
                "{} has a {} `hooks` value, not an object; leaving untouched",
                path.display(),
                other.shape()
            )))
        }
    };
    let script = script_path.to_string_lossy().into_owned();
    for event in CURSOR_HOOK_EVENTS {
        let mut entries = match hooks.remove(event) {
            None => Vec::new(),
            Some(GoValue::Array(items)) => items,
            Some(other) => {
                return Err(PreseedError::failed(format!(
                    "{} has a {} `hooks.{event}` value, not an array; leaving untouched",
                    path.display(),
                    other.shape()
                )))
            }
        };
        if !cursor_hook_entry_present(&entries, &script) {
            // One script serves every event — the event name rides along as
            // argv[1], which is why the whole matrix costs one file. cursor runs
            // `command` through a shell, so the two tokens suffice.
            let mut entry = GoObject::new();
            entry.insert(
                "command".to_string(),
                GoValue::String(format!("{} {event}", shell_quote_always(&script))),
            );
            entries.push(GoValue::Object(entry));
        }
        hooks.insert(event.to_string(), GoValue::Array(entries));
    }
    config.insert("hooks".to_string(), GoValue::Object(hooks));

    atomic_write(
        path,
        HOOKS_TMP_PATTERN,
        marshal_indent(&config).as_bytes(),
        mode,
    )
}

/// Whether one of an event's entries already invokes the hub's script
/// (`cursorHookEntryPresent`, `preseed_cursor.go:316`).
///
/// Matched on the script PATH appearing anywhere in the command — so a
/// hand-edited invocation (extra flags, a wrapper, a different quoting style)
/// counts as ours and is not duplicated on every create — against BOTH the raw
/// path and its [`shell_quote_always`] form, because a path containing a single
/// quote is split across the POSIX `'\''` escape and a raw-only check would miss
/// this preseed's OWN prior entry.
fn cursor_hook_entry_present(entries: &[GoValue], script_path: &str) -> bool {
    let quoted = shell_quote_always(script_path);
    entries.iter().any(|raw| {
        raw.as_object()
            .and_then(|entry| entry.get("command"))
            .and_then(GoValue::as_str)
            .is_some_and(|cmd| cmd.contains(script_path) || cmd.contains(&quoted))
    })
}

#[cfg(test)]
mod tests;
