#!/usr/bin/env bash
# render-dev-mtls-config.sh — render a parallel-dev shed-server config with
# auth.mode: mtls, for SHED_DEV_AUTH_MODE=mtls (see Makefile: dev-server-up,
# dev-server-restart, dev-server-up-fc, dev-server-restart-fc).
#
# Never edits the committed base config (configs/server.dev-parallel.*.yaml).
# Writes a throwaway copy to <output>, regenerated on every invocation, so it
# is safe to run repeatedly and safe to leave un-gitignored garbage behind
# (the caller picks a path under ~/.shed/dev/, which is already scratch space).
#
# The two committed dev-parallel configs start from different auth postures
# today:
#   - configs/server.dev-parallel.mac.yaml already carries an `auth:` block
#     with `mode: token` (plus the https_port + auth.ssh key source mtls also
#     needs) — flipping to mtls is a single-line substitution.
#   - configs/server.dev-parallel.linux-fc.yaml carries NO `auth:` block at
#     all (it runs open, network-facing, for direct FC dev testing) — mtls
#     needs an `auth:` block AND an https_port appended, both invariants the
#     base config lacks (see internal/config/server.go: AuthEnforced).
#
# Either way the SSH key source is `github_users: [charliek]` — the same
# identity already allowlisted by the mac config, so a developer whose default
# SSH key is registered on that GitHub account needs no extra manual step to
# drive the mtls dev server (see tests/integration/test_mtls.py).
set -euo pipefail

if [ "$#" -ne 2 ]; then
  echo "usage: $0 <base-config.yaml> <output-config.yaml>" >&2
  exit 1
fi
base="$1"
out="$2"

if [ ! -f "$base" ]; then
  echo "render-dev-mtls-config: base config not found: $base" >&2
  exit 1
fi

mkdir -p "$(dirname "$out")"

if grep -qE '^auth:[[:space:]]*$' "$base"; then
  # Base config already has an `auth:` block (today: the mac config, mode:
  # token). Flip the mode in place; https_port + auth.ssh are already there.
  if ! grep -qE '^[[:space:]]*mode:[[:space:]]*token[[:space:]]*$' "$base"; then
    echo "render-dev-mtls-config: $base has an 'auth:' block but no" \
         "'mode: token' line to flip; refusing to guess at its shape" >&2
    exit 1
  fi
  sed -E 's/^([[:space:]]*mode:[[:space:]]*)token[[:space:]]*$/\1mtls/' "$base" > "$out"
else
  # No `auth:` block at all (today: the FC config, open mode). Append a
  # top-level `https_port` + `auth:` block. Appending at end-of-file is valid
  # YAML here — these are new top-level (zero-indent) keys, and a mapping key
  # can appear anywhere in the document regardless of what nested block
  # precedes it.
  cp "$base" "$out"
  cat >> "$out" <<'EOF'

# --- Generated by scripts/render-dev-mtls-config.sh for SHED_DEV_AUTH_MODE=mtls ---
# Not committed; regenerated on every dev-server-up/-restart run with
# SHED_DEV_AUTH_MODE=mtls. https_port + auth.ssh are the mtls-mode invariants
# this base config doesn't otherwise carry (see internal/config/server.go).
https_port: 18443
auth:
  mode: mtls
  ssh:
    github_users: [charliek]
EOF
fi

echo "render-dev-mtls-config: wrote $out (auth.mode: mtls)"
