#!/usr/bin/env bash
# render-dev-config.sh — render a throwaway parallel-dev shed-server config
# from a committed base, applying the per-developer overrides the Makefile's
# dev-server targets support (see: dev-server-up, dev-server-restart,
# dev-server-up-fc, dev-server-restart-fc).
#
# Never edits the committed base config (configs/server.dev-parallel.*.yaml).
# Writes to <output>, regenerated on every invocation, so it is safe to run
# repeatedly and safe to leave behind (the caller picks a path under
# ~/.shed/dev/, which is already scratch space). With NO overrides the
# Makefile skips this script entirely and runs the committed config verbatim —
# so a developer who sets nothing gets byte-identical behavior to before this
# script existed.
#
# Usage:
#   render-dev-config.sh <base.yaml> <out.yaml> [--mtls] [--state-dir DIR]
#
# --mtls        SHED_DEV_AUTH_MODE=mtls. The two committed dev-parallel
#               configs start from different auth postures:
#                 - server.dev-parallel.mac.yaml already carries an `auth:`
#                   block with `mode: token` (plus the https_port + auth.ssh
#                   key source mtls also needs) — a one-line substitution.
#                 - server.dev-parallel.linux-fc.yaml carries NO `auth:` block
#                   (it runs open, network-facing, for direct FC dev testing)
#                   — mtls needs an `auth:` block AND an https_port appended,
#                   both invariants that base config lacks (see
#                   internal/config/server.go: AuthEnforced).
#               Either way the SSH key source is `github_users: [charliek]` —
#               the identity the mac config already allowlists, so a developer
#               whose default SSH key is on that GitHub account needs no extra
#               manual step to drive the mtls dev server (tests/integration/
#               test_mtls.py).
#
# --state-dir   SHED_DEV_STATE_DIR. Relocates the dev server's BLOB-HEAVY
#               state — images_dir, instance_dir, snapshots_dir, uppers_dir —
#               under DIR, for a developer whose boot volume cannot host
#               several GB of dev images (this repo's dev store runs ~5 GB+).
#               The committed default stays `~/Library/Application Support/
#               shed-dev/vz`, so this is opt-in per machine and no other
#               developer is affected.
#
#               socket_dir is deliberately NOT relocated. Two reasons: a unix
#               socket path has a hard length limit (~104 bytes on macOS) that
#               a deep external-volume path can breach, and an unmounted
#               volume should fail as "no images" at startup rather than as a
#               confusing mid-run socket error. The brew shed-server on this
#               developer's machine is configured the same way.
set -euo pipefail

usage() {
  echo "usage: $0 <base-config.yaml> <output-config.yaml> [--mtls] [--state-dir DIR]" >&2
  exit 1
}

[ "$#" -ge 2 ] || usage
base="$1"
out="$2"
shift 2

mtls=0
state_dir=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --mtls) mtls=1; shift ;;
    --state-dir) [ "$#" -ge 2 ] || usage; state_dir="$2"; shift 2 ;;
    *) echo "render-dev-config: unknown argument: $1" >&2; usage ;;
  esac
done

if [ ! -f "$base" ]; then
  echo "render-dev-config: base config not found: $base" >&2
  exit 1
fi

# `sed -i` takes an empty backup-suffix argument on BSD (macOS) and rejects one
# on GNU. Pick the form once rather than at every call site.
sed_inplace() {
  if sed --version >/dev/null 2>&1; then
    sed -E -i "$@"          # GNU
  else
    sed -E -i '' "$@"       # BSD / macOS
  fi
}

mkdir -p "$(dirname "$out")"
cp "$base" "$out"
applied=()

# ---- --mtls -----------------------------------------------------------------
if [ "$mtls" = "1" ]; then
  if grep -qE '^auth:[[:space:]]*$' "$out"; then
    # Base already has an `auth:` block (today: the mac config, mode: token).
    # Flip the mode in place; https_port + auth.ssh are already there.
    if ! grep -qE '^[[:space:]]*mode:[[:space:]]*token[[:space:]]*$' "$out"; then
      echo "render-dev-config: $base has an 'auth:' block but no" \
           "'mode: token' line to flip; refusing to guess at its shape" >&2
      exit 1
    fi
    sed_inplace 's/^([[:space:]]*mode:[[:space:]]*)token[[:space:]]*$/\1mtls/' "$out"
  else
    # No `auth:` block at all (today: the FC config, open mode). Append a
    # top-level `https_port` + `auth:` block. Appending at end-of-file is valid
    # YAML here — these are new top-level (zero-indent) keys, and a mapping key
    # can appear anywhere in the document regardless of what nested block
    # precedes it.
    cat >> "$out" <<'EOF'

# --- Generated by scripts/render-dev-config.sh for SHED_DEV_AUTH_MODE=mtls ---
# Not committed; regenerated on every dev-server-up/-restart run with
# SHED_DEV_AUTH_MODE=mtls. https_port + auth.ssh are the mtls-mode invariants
# this base config doesn't otherwise carry (see internal/config/server.go).
https_port: 18443
auth:
  mode: mtls
  ssh:
    github_users: [charliek]
EOF
  fi
  applied+=("auth.mode: mtls")
fi

# ---- --state-dir ------------------------------------------------------------
if [ -n "$state_dir" ]; then
  state_dir="${state_dir%/}"   # strip a trailing slash so paths never double up

  # Rewrite only the blob-heavy dirs, and only where the base actually declares
  # them — a base config that inherits a default for one of these keeps
  # inheriting it rather than silently gaining an override this script
  # invented. Each substitution is anchored to the key at line start (with its
  # own indent preserved), so a VALUE containing the key name cannot be hit.
  rewrote=0
  for key in images_dir instance_dir snapshots_dir uppers_dir; do
    grep -qE "^[[:space:]]*${key}:" "$out" || continue
    case "$key" in
      images_dir)    sub="$state_dir" ;;
      instance_dir)  sub="$state_dir/instances" ;;
      snapshots_dir) sub="$state_dir/snapshots" ;;
      uppers_dir)    sub="$state_dir/uppers" ;;
    esac
    sed_inplace "s|^([[:space:]]*)${key}:[[:space:]]*.*$|\\1${key}:    ${sub}|" "$out"
    rewrote=$((rewrote + 1))
  done

  if [ "$rewrote" -eq 0 ]; then
    echo "render-dev-config: --state-dir was given but $base declares none of" \
         "images_dir/instance_dir/snapshots_dir/uppers_dir; refusing to" \
         "silently do nothing" >&2
    exit 1
  fi

  cat >> "$out" <<EOF

# --- Generated by scripts/render-dev-config.sh for SHED_DEV_STATE_DIR ---
# The $rewrote blob-heavy state dir(s) above were rewritten under
#   $state_dir
# socket_dir is deliberately left where the base config put it (unix socket
# path length limits; see the script header).
EOF
  applied+=("state dir: $state_dir")
fi

if [ "${#applied[@]}" -eq 0 ]; then
  echo "render-dev-config: no overrides requested — the caller should have run" \
       "the committed base config directly" >&2
  exit 1
fi

joined=""
for a in "${applied[@]}"; do
  [ -z "$joined" ] && joined="$a" || joined="$joined, $a"
done
echo "render-dev-config: wrote $out ($joined)"
