package main

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"log/slog"
	"math/rand/v2"
	"net"
	"os"
	"path/filepath"
	"strconv"
	"sync"
	"time"

	"github.com/charliek/shed/internal/clienttoken"
	sdk "github.com/charliek/shed/sdk"
	sdkbootstrap "github.com/charliek/shed/sdk/bootstrap"
	"github.com/charliek/shed/sdk/creds"
	"golang.org/x/crypto/ssh"
	"golang.org/x/crypto/ssh/knownhosts"
)

// CredentialMinter bootstraps the host-agent's own credential over a server's
// SSH _bootstrap channel by invoking the system ssh client (via sdk/bootstrap).
// The agent authenticates with a key already on the server's allowlist (the same
// key `shed server add` used) — resolved by ssh from the agent, macOS Keychain,
// 1Password/Secretive IdentityAgent, hardware keys, or ~/.ssh/config — and the
// server issues a short-TTL credential bound to that key. No private key
// material belonging to the SSH identity is read by the host-agent itself.
//
// The exchange is CSR-first and mode-agnostic: a fresh P-256 keypair is
// generated per mint and its CSR submitted alongside the request, so the SERVER
// decides whether the answer is a bearer token or a client certificate. That is
// what lets one agent work against a token-mode server, an mtls-mode server, and
// a server that gets flipped between them while the agent is running — without
// any local configuration saying which.
type CredentialMinter struct {
	knownHostsPath string // where the server's SSH host key is pinned (~/.shed/known_hosts)

	// bootstrapRun runs the SSH bootstrap exchange; a field so tests can inject a
	// fake without spawning ssh or standing up a server. Defaults to
	// sdkbootstrap.RunCredential.
	bootstrapRun func(context.Context, sdkbootstrap.Params) (sdk.Credential, error)

	// relayRun runs a bootstrap with a CSR the CALLER generated, returning the
	// bundle without a private key (the desktop relay — see MintRelayed).
	// Defaults to sdkbootstrap.RunWithCSR.
	relayRun func(context.Context, sdkbootstrap.Params) (sdk.Bundle, error)
}

// NewCredentialMinter builds a minter from the known_hosts file that pins server
// host keys (tilde-expanded). The SSH identity is resolved by the system ssh
// client (agent/Keychain/IdentityAgent/config), not read from a fixed key file.
func NewCredentialMinter(knownHostsPath string) *CredentialMinter {
	return &CredentialMinter{
		knownHostsPath: expandTilde(knownHostsPath),
		bootstrapRun:   sdkbootstrap.RunCredential,
		relayRun:       sdkbootstrap.RunWithCSR,
	}
}

// Credential scopes the host-agent mints over SSH: credentials for its own bus
// brokering, control for a credential.get/token.get on the desktop's behalf.
const (
	scopeCredentials = "credentials"
	scopeControl     = "control"
)

// clientKindHostAgent is the advisory client kind stamped on every credential
// the agent mints — including the ones it relays for the desktop, because the
// SSH key doing the authenticating is the agent's.
const clientKindHostAgent = "host-agent"

// Mint bootstraps a fresh credential of the given scope for t over its SSH
// endpoint. ssh verifies the server's host key against the pin already in
// known_hosts (the same trust `shed server add` established), so this never
// trusts an unpinned server.
func (m *CredentialMinter) Mint(ctx context.Context, t ServerTarget, scope string) (sdk.Credential, error) {
	if err := m.checkPinned(t); err != nil {
		return sdk.Credential{}, err
	}
	cred, err := m.bootstrapRun(ctx, m.params(t, scope, ""))
	if err != nil {
		return sdk.Credential{}, fmt.Errorf("bootstrapping %s credential for %q: %w", scope, t.Name, err)
	}
	return cred, nil
}

// MintRelayed bootstraps a credential using a CSR generated by SOMEONE ELSE —
// the desktop app, whose private key stays in the app process. The returned
// bundle carries the issued certificate (or, against a token-mode server, a
// token) and no key: this side never had one.
//
// csrBase64 may be empty, which makes the exchange CSR-free; against an mtls
// server that yields the server's own explicit upgrade error, which is the
// truthful answer to relay back to an app that sent no CSR.
func (m *CredentialMinter) MintRelayed(ctx context.Context, t ServerTarget, scope, csrBase64 string) (sdk.Bundle, error) {
	if err := m.checkPinned(t); err != nil {
		return sdk.Bundle{}, err
	}
	bundle, err := m.relayRun(ctx, m.params(t, scope, csrBase64))
	if err != nil {
		return sdk.Bundle{}, fmt.Errorf("bootstrapping %s credential for %q: %w", scope, t.Name, err)
	}
	return bundle, nil
}

func (m *CredentialMinter) params(t ServerTarget, scope, csrBase64 string) sdkbootstrap.Params {
	return sdkbootstrap.Params{
		Host:           t.SSHHost,
		Port:           t.SSHPort,
		KnownHostsPath: m.knownHostsPath,
		Scope:          scope,
		ClientKind:     clientKindHostAgent,
		CSRBase64:      csrBase64,
	}
}

// checkPinned pre-checks that the server is pinned. This is NOT a safety latch —
// a missing pin is already non-terminal/retryable downstream (ssh + sdk/bootstrap
// classify it as a verification failure, never as a host-key mismatch). It buys
// two things: an actionable "run shed server add" error instead of ssh's opaque
// "Host key verification failed", and skipping a doomed ssh spawn.
func (m *CredentialMinter) checkPinned(t ServerTarget) error {
	return knownHostsPinned(m.knownHostsPath, t.SSHHost, t.SSHPort)
}

// knownHostsPinned reports whether the known_hosts file has a usable (non-revoked,
// non-CA) host-key entry pinning host:port — the same trust anchor `shed server
// add` wrote via AddKnownHost. It is a presence predicate: ssh re-verifies the pin
// authoritatively during the exchange, so only the existence of an entry matters
// here, not its value. Returns nil when one is present, and an error when the file
// is unreadable, unparseable, or has no entry for the endpoint. (ssh prints the
// same "Host key verification failed" for a missing entry and a garbled file, so
// this in-process read is the only reliable way to give the actionable "run `shed
// server add` first" message instead.)
func knownHostsPinned(knownHostsPath, host string, port int) error {
	data, err := os.ReadFile(knownHostsPath)
	if err != nil {
		return fmt.Errorf("reading known_hosts %s: %w", knownHostsPath, err)
	}
	// knownhosts.Normalize yields the stored form: "[host]:port" for a non-22
	// port, bare "host" for port 22 — matching how OpenSSH (and shed) records it.
	want := knownhosts.Normalize(net.JoinHostPort(host, strconv.Itoa(port)))
	for len(data) > 0 {
		marker, hosts, _, _, rest, err := ssh.ParseKnownHosts(data)
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("parsing known_hosts %s: %w", knownHostsPath, err)
		}
		data = rest
		// Skip marked lines: a @revoked key must never be used as a pin, and a
		// @cert-authority line is a CA, not a host-key pin.
		if marker != "" {
			continue
		}
		for _, h := range hosts {
			if h == want {
				return nil
			}
		}
	}
	return fmt.Errorf("no host key pinned for %s in %s (run `shed server add` first)", want, knownHostsPath)
}

const (
	// The proactive refresh loop re-mints at ~50% of the time remaining until
	// expiry, jittered, clamped to [minRefreshDelay, maxRefreshDelay]; it uses
	// defaultRefreshDelay until a credential has been minted.
	defaultRefreshDelay = time.Hour
	minRefreshDelay     = time.Minute
	maxRefreshDelay     = 12 * time.Hour
	// jitterFraction de-synchronizes a fleet re-minting together: the delay is
	// spread ±jitterFraction around its base.
	jitterFraction = 0.25
)

// minter is the subset of CredentialMinter that credentialSource needs; an
// interface so tests can inject a fake without a live SSH server.
type minter interface {
	Mint(ctx context.Context, t ServerTarget, scope string) (sdk.Credential, error)
}

// hostAgentCredStore returns the agent's OWN credential store for a scope.
//
// It is deliberately not ~/.shed/creds: that directory belongs to the shed CLI's
// control-scope certificate, and one certificate carries exactly one scope. Two
// processes rotating independently into the same per-server directory would
// overwrite each other's material in place — the agent would keep replacing the
// CLI's control certificate with its credentials-scoped one and vice versa, and
// each would then present a certificate the server refuses for the route it is
// calling. Separate roots, one implementation (sdk/creds).
//
// The scope is a path component so the two scopes a single agent can hold never
// collide either.
func hostAgentCredStore(scope string) *creds.Store {
	return creds.NewStore(filepath.Join(stateDir(), "host-agent", "creds", scope))
}

// credentialSource is the host-agent's per-server, per-scope credential: an
// sdk.TokenProvider AND an sdk.ClientCertProvider over one clienttoken.Source.
//
// Both interfaces are satisfied by the same object on purpose. A bearer token
// and a client certificate are not two credentials to choose between but two
// shapes of the same one, and which shape is held is decided by the server at
// each mint. Splitting them would mean something local had to predict the mode.
//
// A host-key pin mismatch is TERMINAL — a possible MITM — so the source fails
// closed and never mints for that server again, rather than downgrading to a
// weaker credential.
type credentialSource struct {
	src    *clienttoken.Source
	target ServerTarget
	scope  string
	// store persists the minted certificate so a restart does not have to
	// re-enroll over SSH. nil disables persistence (the control-scope source the
	// desktop path uses, which deliberately keeps nothing).
	store  *creds.Store
	logger *slog.Logger

	mu       sync.Mutex
	terminal error
}

// newCredentialSource builds the credential source for one server + scope,
// seeded from whatever is already on disk (or from the entry's static token).
// store may be nil to disable persistence.
func newCredentialSource(ctx context.Context, m minter, t ServerTarget, scope string, store *creds.Store, logger *slog.Logger) *credentialSource {
	s := &credentialSource{target: t, scope: scope, store: store, logger: logger}
	s.src = clienttoken.New(s.seed(), func() (clienttoken.Credential, error) {
		return s.mint(ctx, m)
	})
	return s
}

// seed is the credential the source starts with, before any mint.
//
// A persisted certificate is loaded only when the recorded auth_mode says the
// server issues them. That is not an optimization: loading one unconditionally
// would present a stale certificate to a server that has since been flipped back
// to token mode, and the flip is supposed to be invisible. When in doubt the
// source starts empty, and EnsureFresh mints before the first request.
func (s *credentialSource) seed() clienttoken.Credential {
	if s.store != nil && s.target.IsMTLS() && s.target.Name != "" {
		cert, err := s.store.LoadServer(s.target.Name)
		switch {
		case err == nil:
			return clienttoken.MTLSCredential(cert, certificateExpiry(cert))
		case errors.Is(err, fs.ErrNotExist):
			// Nothing stored yet — a first start, or a server that has only ever
			// been reached in token mode. Not worth a log line.
		default:
			// Unreadable, malformed, or a mismatched pair (the shape a crash
			// between the two renames of a rotation leaves). All of them mean the
			// same thing here — enroll fresh — but they are worth saying out loud,
			// because "silently re-enrolled every start" is otherwise invisible.
			s.debug("no usable stored certificate; will re-enroll", "error", err)
		}
	}
	if s.target.Token != "" {
		// A statically configured credentials_token. Zero expiry: nothing local
		// knows when it stops working, so it is never proactively re-minted —
		// only replaced once a real mint returns something better.
		return clienttoken.TokenCredential(s.target.Token, time.Time{})
	}
	return clienttoken.Credential{}
}

// certificateExpiry reads a certificate's NotAfter, which is what the refresh
// window is measured against. A leaf that cannot be parsed yields a zero time —
// "never proactively re-mint" — rather than an error: the certificate still
// works until the server says otherwise, and the reactive path covers that.
func certificateExpiry(cert *tls.Certificate) time.Time {
	if cert == nil {
		return time.Time{}
	}
	if cert.Leaf != nil {
		return cert.Leaf.NotAfter
	}
	if len(cert.Certificate) == 0 {
		return time.Time{}
	}
	leaf, err := x509.ParseCertificate(cert.Certificate[0])
	if err != nil {
		return time.Time{}
	}
	return leaf.NotAfter
}

// mint is the refresh callback: one SSH bootstrap, adopt whatever came back.
func (s *credentialSource) mint(ctx context.Context, m minter) (clienttoken.Credential, error) {
	s.mu.Lock()
	terminal := s.terminal
	s.mu.Unlock()
	if terminal != nil {
		return clienttoken.Credential{}, terminal
	}

	res, err := m.Mint(ctx, s.target, s.scope)
	if err != nil {
		if errors.Is(err, sdkbootstrap.ErrHostKeyMismatch) {
			err = fmt.Errorf("refusing to broker %q: SSH host key pin mismatch (possible MITM): %w", s.target.Name, err)
			s.mu.Lock()
			s.terminal = err
			s.mu.Unlock()
		}
		return clienttoken.Credential{}, err
	}
	return s.adopt(res)
}

// adopt turns a bootstrap result into the live credential and persists the mtls
// half.
//
// The persist is best-effort in both directions and deliberately so: the
// credential in memory is already valid, so failing the mint because the disk is
// full would turn a recoverable annoyance into an outage. What it costs is one
// extra SSH round-trip after a restart.
func (s *credentialSource) adopt(res sdk.Credential) (clienttoken.Credential, error) {
	if res.Mode() != sdk.AuthModeMTLS {
		// Token mode — including a server that just flipped BACK from mtls. The
		// stored certificate is now inert material for a mode this server no
		// longer serves, so it is removed rather than left to be loaded (and
		// presented) by the next start.
		s.discardStored()
		return clienttoken.TokenCredential(res.Bundle.Token, res.Bundle.ExpiresAt), nil
	}
	cert, err := tls.X509KeyPair([]byte(res.Bundle.ClientCert), res.KeyPEM)
	if err != nil {
		return clienttoken.Credential{}, fmt.Errorf("assembling issued client certificate for %q: %w", s.target.Name, err)
	}
	s.persist(res)
	return clienttoken.MTLSCredential(&cert, res.Bundle.ExpiresAt), nil
}

// persist stores the issued pair. A nameless target — single-server mode, where the
// agent watches one URL and no discovery name exists — stores nothing: the store is
// keyed by server name, and inventing one would be a directory nothing ever reads
// back. Such an agent re-enrolls on restart, which is the same cost it has always paid.
func (s *credentialSource) persist(res sdk.Credential) {
	if s.store == nil || s.target.Name == "" {
		return
	}
	if _, _, err := s.store.Write(s.target.Name, []byte(res.Bundle.ClientCert), res.KeyPEM); err != nil {
		s.warn("could not persist the issued client certificate; will re-enroll after a restart", "error", err)
	}
}

func (s *credentialSource) discardStored() {
	if s.store == nil || s.target.Name == "" {
		return
	}
	if err := s.store.Remove(s.target.Name); err != nil {
		s.warn("could not remove stale client certificate", "error", err)
	}
}

// Token returns the current bearer token, minting first when there is nothing
// usable or the credential is near expiry. Implements sdk.TokenProvider.
//
// In mtls state it returns "" with a nil error, which is exactly right: the
// credential is real and current, it simply is not a bearer token, and the
// caller's certificate path carries it instead. An error here means there is no
// credential of ANY shape.
func (s *credentialSource) Token() (string, error) {
	if err := s.src.EnsureFreshErr(); err != nil {
		return "", err
	}
	return s.src.Token(), nil
}

// ClientCertificate returns the certificate to present at a TLS handshake, or
// nil in token state. Implements sdk.ClientCertProvider.
//
// It never mints: it is called from the TLS stack, on the dialing goroutine, at
// a point where an SSH round-trip would stall the handshake behind a network
// operation the handshake's own deadline knows nothing about. The mint happens
// earlier, in Token, which every request path calls before it dials.
func (s *credentialSource) ClientCertificate() *tls.Certificate {
	return s.src.ClientCertificate()
}

// Invalidate re-mints because the server refused what was presented (a 401, or
// a TLS alert naming the certificate). Implements sdk.TokenProvider.
//
// It is generation-aware and coalesced: a caller whose credential was already
// replaced by a concurrent re-mint does not trigger a second one. A failed
// re-mint leaves the existing credential in place — presenting something the
// server MIGHT still accept beats presenting nothing, and the error surfaces on
// the next Token.
func (s *credentialSource) Invalidate() { _ = s.reMint() }

// reMint replaces the current credential unconditionally, coalescing concurrent
// callers onto one mint and skipping the work entirely for a caller whose
// credential was already replaced.
func (s *credentialSource) reMint() error {
	_, gen := s.src.Current()
	_, err := s.src.Refresh(gen)
	return err
}

// Mode reports the shape of the credential currently held ("token", "mtls", or
// "" for none) — used by `status` and by the tests that assert a flip landed.
func (s *credentialSource) Mode() string { return s.src.Mode() }

// refresh proactively re-mints, best-effort (errors surface on the next Token).
// Driven by refreshLoop so an idle server's credential stays fresh.
//
// It re-mints unconditionally rather than only inside the expiry window: the
// loop's own schedule (~50% of the remaining lifetime) IS the policy, and
// deferring to the window would collapse it to "re-mint in the last two hours",
// discarding the spread that keeps a fleet from re-enrolling in lockstep.
func (s *credentialSource) refresh() {
	if err := s.reMint(); err != nil {
		s.debug("proactive credential refresh failed", "error", err)
	}
}

// refreshLoop proactively re-mints at ~50% of the time until expiry (jittered),
// so an idle server's credential stays fresh and a fleet re-minting after a
// server restart is spread out rather than thundering. Stops when ctx is done.
func (s *credentialSource) refreshLoop(ctx context.Context) {
	for {
		select {
		case <-ctx.Done():
			return
		case <-time.After(s.nextRefreshDelay()):
		}
		if ctx.Err() != nil {
			return
		}
		s.refresh()
	}
}

// nextRefreshDelay is ~50% of the time until the cached credential expires,
// jittered ±25%, clamped to [minRefreshDelay, maxRefreshDelay];
// defaultRefreshDelay when nothing has been minted yet.
func (s *credentialSource) nextRefreshDelay() time.Duration {
	exp := s.src.ExpiresAt()

	base := defaultRefreshDelay
	if !exp.IsZero() {
		if remaining := time.Until(exp); remaining > 0 {
			base = remaining / 2
		} else {
			base = minRefreshDelay
		}
	}
	// (2*rand-1) is uniform in [-1,1), so this spreads d by ±jitterFraction of base.
	d := base + time.Duration((2*rand.Float64()-1)*jitterFraction*float64(base))
	return min(max(d, minRefreshDelay), maxRefreshDelay)
}

func (s *credentialSource) warn(msg string, args ...any) {
	if s.logger != nil {
		s.logger.Warn(msg, append([]any{"server", s.target.Name, "scope", s.scope}, args...)...)
	}
}

func (s *credentialSource) debug(msg string, args ...any) {
	if s.logger != nil {
		s.logger.Debug(msg, append([]any{"server", s.target.Name, "scope", s.scope}, args...)...)
	}
}
